apiVersion: v1
kind: Service
metadata:
  name: selenium-node-chrome
  labels:
    app: selenium-node-chrome
spec:
  ports:
  - port: 5555
    targetPort: 5555
    name: port0
  selector:
    app: selenium-node-chrome
  type: NodePort
  sessionAffinity: None