apiVersion: v1
kind: Service
metadata:
  name: selenium-node-firefox
  labels:
    app: selenium-node-firefox
spec:
  ports:
  - port: 5900
    targetPort: 5900
    name: port0
  selector:
    app: selenium-node-firefox
  type: NodePort
  sessionAffinity: None